### ISSUE TITLE
stylex-webpack doesn't work properly in Next.js development environment

### ISSUE THREAD

**Issue by Allenyou1126** [SukkaW/stylex-webpack#4]
I added `@stylexjs/stylex` and `stylex-webpack` into my project, but when I launched the dev server, I got an error in the console and the it didn't work as expected.

The error log is below:

```
Error: 'stylex.create' should never be called at runtime. It should be compiled away by '@stylexjs/babel-plugin'
    at errorForFn (webpack-internal:///(rsc)/./node_modules/@stylexjs/stylex/lib/es/stylex.mjs:189:28)
    at Function.stylexCreate [as create] (webpack-internal:///(rsc)/./node_modules/@stylexjs/stylex/lib/es/stylex.mjs:228:9)
    at eval (webpack-internal:///(rsc)/./src/app/layout.tsx:15:73)
    at (rsc)/./src/app/layout.tsx (D:\Project\Website\stylex-webpack-issue-reproduction\.next\server\app\page.js:97:1)
    at Function.__webpack_require__ (D:\Project\Website\stylex-webpack-issue-reproduction\.next\server\webpack-runtime.js:33:42)
    at async e7 (D:\Project\Website\stylex-webpack-issue-reproduction\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:396619)
    at async tS (D:\Project\Website\stylex-webpack-issue-reproduction\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400214)
    at async tw (D:\Project\Website\stylex-webpack-issue-reproduction\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400775)
    at async tO (D:\Project\Website\stylex-webpack-issue-reproduction\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2320)
    at async D:\Project\Website\stylex-webpack-issue-reproduction\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2989 {
  digest: '1747662813',
  page: '/'
```

I've created a minium bug reproduction [here](https://github.com/Allenyou1126/stylex-webpack-issue-reproduction), and I hope that will help someone find out a solution easier.

**Comment by Allenyou1126** [comment]
Hi, it has been two weeks since the issue was opened. Is there anyone able to offer some suggestions about how to solve the problem or where to get help about my problem? I'd sincerely appreciate it if someone helps.

**Comment by SukkaW** [comment]
Have you tried rename `next.config.cjs` to `next.config.js`?

**Comment by Allenyou1126** [comment]
> Have you tried rename `next.config.cjs` to `next.config.js`?
> 
> `next.config.cjs` is never supported by Next.js: https://github.com/vercel/next.js/blob/47e346c97bcb54179eb409ad12757a13b5a0fb13/packages/next/src/shared/lib/constants.ts#L53

yes，it works for my problem, thank you for your help.
